# Generated by Django 2.1.3 on 2018-11-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('code', models.CharField(max_length=10, verbose_name='コード')),
                ('lang', models.CharField(max_length=10, verbose_name='言語')),
            ],
            options={
                'verbose_name': '色',
                'verbose_name_plural': '色',
                'db_table': 'color',
            },
        ),
    ]
