# Generated by Django 2.1.3 on 2018-11-18 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='色名')),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.Lang'),
        ),
    ]
