# Generated by Django 2.1.3 on 2018-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0003_auto_20181118_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名前'),
        ),
    ]
